### ISSUE TITLE
Maven doesn't work

### ISSUE THREAD

**Issue by marekkondracki** [mirego/trikot#173]
I have tried to download KWord to the kotlin multi project and it couldn't find library.

"https://s3.amazonaws.com/mirego-maven/public"

this maven url returns access denied.

**Comment by marcantoinefortier** [comment]
Hi @marekkondracki , could you provide your [installation setup](https://github.com/mirego/trikot/tree/master/trikot-kword#installation) from your `build.gradle.kts` and your exact error log? 

This would help us pinpoint the exact cause of your issue. 🙏🏻

**Comment by marekkondracki** [comment]
@marcantoinefortier it looks like temporary problem with AWS few hours ago. Now I can download these files from maven. In the meanwhile I tried setup mirego boilerplate project with kword plugi. Implementing it, according to instructions in readme, unfortunately, it doesn't work...
