### ISSUE TITLE
Can NEW_MM be used in production environment? Which app use NEW_MM mode?

### ISSUE THREAD

**Issue by libill** [mirego/trikot#64]
From https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md ，it list some Performance issues and Known bugs.  Trikot Already used NEW_MM, kotlin.native.binary.memoryModel=experimental. Can NEW_MM be used in production environment? Which app use NEW_MM mode?

**Comment by npresseault** [comment]
> Trikot Already used NEW_MM, kotlin.native.binary.memoryModel=experimental

That is not entirely true. `Trikot sample projects` use the new MM. The libraries themselves are not forcing the new memory model as this choice is up to the client app. 

However `Trikot` itself will remain useable in both modes (old and new memory model) for a little while (no specific ETA for this).

To the question can NEW_MM be used in production environment, I would say that you should read Jetbrains documentation, bug tracker and disclaimers and make the choice for yourself. We cannot advice you on this subject.
